[build]
  command = "mkdir -p functions && go get ./... && go build -o functions/ ./cmd/cronometer "
  functions = "functions"
[build.environment]
  GO_IMPORT_PATH = "github.com/jonpitch/intervals-functions"