[build]
  command = "mkdir -p functions && go get ./... && CGO_ENABLED=0 go build -o functions/ ./cmd/cronometer"
  functions = "functions"
[build.environment]
  GO_IMPORT_PATH = "github.com/jonpitch/intervals-functions"
[functions."cronometer"]
  schedule = "0 5 * * *"